DEVOPS-853 add check-jira-issue to other workflow file

diff --git a/.github/workflows/reusable-jira-pr_add_jira_summary.yml b/.github/workflows/reusable-jira-pr_add_jira_summary.yml
--- a/.github/workflows/reusable-jira-pr_add_jira_summary.yml
+++ b/.github/workflows/reusable-jira-pr_add_jira_summary.yml
@@ -16,17 +16,17 @@ on:
         required: true
         description: The API token for your JIRA account
 
+env:
+  JIRA_PATTERN: "([A-Z]+)[-# ]*([0-9]+)"
+  JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
+  JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
+  JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
 
 jobs:
   add_jira_summary:
     if: ${{ github.event.action == 'opened' }}
     runs-on: ubuntu-latest
     timeout-minutes: 20
-    env:
-      JIRA_PATTERN: "([A-Z]+)[-# ]*([0-9]+)"
-      JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
-      JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
-      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
 
     steps:
 
@@ -100,3 +100,64 @@ jobs:
         -H "Content-Type: application/json"
         "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/pulls/${{ github.event.pull_request.number }}"
         > /dev/null
+
+  check_jira_issue:
+    runs-on: ubuntu-latest
+    timeout-minutes: 20
+
+    steps:
+
+    - name: Find JIRA issue key from title
+      id: jira_key_from_title
+      if: ${{ !steps.jira_summary_from_branch.outputs.summary }}
+      env:
+        PR_TITLE: ${{ github.event.pull_request.title }}
+      run: >
+        echo "issue_key=$(
+        echo $PR_TITLE | grep -osiE "^\s*\[?\s*$JIRA_PATTERN"
+        | head -n1 | sed -E "s/\W*$JIRA_PATTERN/\1-\2/i"
+        | tr [:lower:] [:upper:]
+        )" >> $GITHUB_OUTPUT
+
+    - name: Check issue key
+      if: ${{ !steps.jira_key_from_title.outputs.issue_key }}
+      run: |
+        echo "Could not determine Jira issue from PR title"
+        exit 1
+
+    - name: Check issue status
+      if: ${{ steps.jira_key_from_title.outputs.issue_key }}
+      run: | 
+        jql="Sprint in (openSprints(), futureSprints()) and issue=${{ steps.jira_key_from_title.outputs.issue_key }}"
+        jqlencoded=$(jq -R -r @uri <<<"$jql")
+        response=$(curl -s --request GET \
+                   --url "$JIRA_BASE_URL/rest/api/3/search/jql?jql=$jqlencoded&fields=statusCategory" \
+                   --user "${JIRA_USER_EMAIL}:${JIRA_API_TOKEN}" \
+                   --header 'Accept: application/json' \
+                   --header 'Content-Type: application/json')
+
+        if [ $? -ne 0 ]; then
+            echo "Jira API: error"
+            exit 1
+        fi
+
+        echo "response was: $(echo $response|jq)"
+        error=""
+
+        echo "Checking if issue is in open or future sprint"
+        sprint=$(echo $response | jq '.issues | length')
+        if [ $sprint -eq 0 ]; then
+            error="Error: Jira issue is not in open or future sprint"
+        fi
+
+        echo "Checking if issue is In Progress"
+        status=$(echo $response| jq -r '.issues[0].fields.statusCategory.name')
+        if [ "$status" != "In Progress" ]; then
+            error="$error Error: Jira issue is not In Progress"
+        fi
+
+        if [[ ! -z "$error" ]]; then
+            echo $error
+            exit 1
+        fi
+
