[DEVOPS-504] Create a workflow which build conda package

diff --git a/.github/workflows/reusable-python-publish_package.yml b/.github/workflows/reusable-python-publish_package.yml
--- a/.github/workflows/reusable-python-publish_package.yml
+++ b/.github/workflows/reusable-python-publish_package.yml
@@ -3,11 +3,11 @@ name: Publish condan package to Artifactory
 on:
   workflow_call:
     inputs:
-        package-manager:
-            description: 'Package manager to use (eg. "conda", "poetry", "hatch")'
+        package-managers:
+            description: 'Matrix of Package manager to use (eg. ["conda", "poetry", "hatch"])'
             required: true
             type: string
-            default: 'poetry'
+            default: '["poetry"]'
         package-name:
             description: 'Name of the package to build'
             required: true
@@ -62,49 +62,31 @@ defaults:
         shell: 'bash -l {0}'
 
 jobs:
-    release_pypi_package:
-        name: Release PyPI package
+    release_package:
+        name: Release package
+        strategy:
+            matrix:
+                package-manager: ${{ fromJSON(inputs.package-managers) }}
         runs-on: ubuntu-latest
+        defaults:
+            run:
+                shell: 'bash -l {0}'
         timeout-minutes: ${{ inputs.timeout-minutes }}
-        if: ${{ inputs.package-manager != 'conda' }}
         steps:
-            -   uses: actions/checkout@v4
-                with:
-                    lfs: ${{ inputs.lfs }}
-                    fetch-depth: 0
-            -   name: Set up Python version
-                uses: actions/setup-python@v5
+            -   uses: MiraGeoscience/CI-tools/.github/workflow/reusable-python-build_conda.yml@DEVOPS-504
+                name: Build conda package
+                if: ${{ matrix.package-manager == 'conda' }}
                 with:
                     python-version: ${{ inputs.python-version }}
-            
-            -   uses: MiraGeoscience/CI-tools/.github/actions/reusable-python-setup_poetry@main
-                name: Setup poetry env
-                if: ${{ inputs.package-manager == 'poetry' }}
-                with:
-                    cache-number: 1
-                    runner-os: ${{ runner.os }}
-                    extra-repository: ${{ inputs.extra-repository }}
-                    repo-user: ${{ secrets.EXTRA_PYPI_REPO_USER }}
-                    repo-token: ${{ secrets.EXTRA_PYPI_REPO_TOKEN }}
-            -   uses: MiraGeoscience/CI-tools/.github/actions/reusable-python-setup_hatch@main
-                name: Setup hatch env
-                if: ${{ inputs.package-manager == 'hatch' }}
-                with:
-                    cache-number: 1
-                    runner-os: ${{ runner.os }}
-            
-            -   name: Build package
+                    lfs: ${{ inputs.lfs }}
+                    timeout-minutes: ${{ inputs.timeout-minutes }}
+            -   name: Check if there is some artifact
                 run: |
-                    if ${{ inputs.package-manager == 'poetry' }}; then
-                        poetry build
-                    elif ${{ inputs.package-manager == 'hatch'}}; then
-                        hatch build
-                    else
-                        echo "Unknown pypi package manager. ${{ inputs.package-manager }} is not part of ['hatch', 'poetry']."
-                        exit 1
-                    fi
-            -   name: Setup JFrog CLI
-                uses: jfrog/setup-jfrog-cli@v4.4.1
+                    ls .
+                    ls dist
+            
+            -   uses: jfrog/setup-jfrog-cli@v4.4.1
+                name: Setup JFrog CLI
                 env:
                     JF_URL: ${{ secrets.JFROG_ARTIFACTORY_URL }}
                     JF_ACCESS_TOKEN: ${{ secrets.JFROG_ARTIFACTORY_TOKEN }}
@@ -118,65 +100,118 @@ jobs:
                         echo "Uploading in: ${repo_name}/${{ inputs.package-name }}/${{ inputs.version-tag }}/"
                         jf rt u dist/* ${repo_name}/${{ inputs.package-name }}/${{ inputs.version-tag }}/
                     done
-                    
-                    
-    release_conda_package:
-        name: Release Conda package
-        runs-on: ubuntu-latest
-        timeout-minutes: ${{ inputs.timeout-minutes }}
-        if: ${{ inputs.package-manager == 'conda' }}
-        steps:
-            -   name: Checkout
-                uses: actions/checkout@v2
-                with:
-                    lfs: ${{ inputs.lfs }}
-            -   name: Check if the version tag is available
-                run: |
-                    if [ "${{ inputs.version-tag }}" = "v0.0.0" ]; then
-                        echo "Version tag not available"
-                        exit 1
-                    else
-                        echo "Version tag available"
-                    fi
-            # -   name: Check if there is a conda recipe
-            #     run: |
-            #         ls .
-            #         if [ -f meta.yaml ]; then
-            #             echo "Conda recipe found"
-            #         else
-            #             echo "Conda recipe not found"
-            #             exit 1
-            #         fi
-            -   name: Setup conda env
-                uses: mamba-org/setup-micromamba@v1
-                with:
-                    micromamba-version: 1.5.8-0
-                    environment-name: test_env
-                    init-shell: bash
-                    cache-downloads: true
-                env:
-                    PYTHONUTF8: 1
-                    CONDA_CHANNEL_PRIORITY: strict
-                    PIP_NO_DEPS: 1 # all dependencies are installed from conda
-            -   name: Install conda build
-                run: conda install -y conda-build conda-verify
-            -   name: Build package
-                id: build_package
-                run: |
-                    conda build .
-                    build_path=$(conda build --output .)
-                    build_name=$(basename ${build_path})
-                    echo "BUILD_PATH=${build_path}" >> $GITHUB_ENV
-                    echo "BUILD_NAME=${build_name}" >> $GITHUB_ENV
+
+    # release_pypi_package:
+    #     name: Release PyPI package
+    #     runs-on: ubuntu-latest
+    #     timeout-minutes: ${{ inputs.timeout-minutes }}
+    #     if: ${{ inputs.package-manager != 'conda' }}
+    #     steps:
+    #         -   uses: actions/checkout@v4
+    #             with:
+    #                 lfs: ${{ inputs.lfs }}
+    #                 fetch-depth: 0
+    #         -   name: Set up Python version
+    #             uses: actions/setup-python@v5
+    #             with:
+    #                 python-version: ${{ inputs.python-version }}
             
-            -   name: Setup JFrog CLI
-                uses: jfrog/setup-jfrog-cli@v4.4.1
-                env:
-                    JF_URL: ${{ secrets.JFROG_ARTIFACTORY_URL }}
-                    JF_ACCESS_TOKEN: ${{ secrets.JFROG_ARTIFACTORY_TOKEN }}
-            -   name: Publish package to Artifactory
-                run: |
-                    repository_list=$(echo '${{ inputs.repo-names }}' | jq -r '.[]')
-                    for repo_name in ${repository_list}; do
-                        jf rt u ${{ env.BUILD_PATH }} ${repo_name}/${{ inputs.package-name }}/${{ inputs.version-tag }}/${{ env.BUILD_NAME }}
-                    done
+    #         -   uses: MiraGeoscience/CI-tools/.github/actions/reusable-python-setup_poetry@main
+    #             name: Setup poetry env
+    #             if: ${{ inputs.package-manager == 'poetry' }}
+    #             with:
+    #                 cache-number: 1
+    #                 runner-os: ${{ runner.os }}
+    #                 extra-repository: ${{ inputs.extra-repository }}
+    #                 repo-user: ${{ secrets.EXTRA_PYPI_REPO_USER }}
+    #                 repo-token: ${{ secrets.EXTRA_PYPI_REPO_TOKEN }}
+    #         -   uses: MiraGeoscience/CI-tools/.github/actions/reusable-python-setup_hatch@main
+    #             name: Setup hatch env
+    #             if: ${{ inputs.package-manager == 'hatch' }}
+    #             with:
+    #                 cache-number: 1
+    #                 runner-os: ${{ runner.os }}
+            
+    #         -   name: Build package
+    #             run: |
+    #                 if ${{ inputs.package-manager == 'poetry' }}; then
+    #                     poetry build
+    #                 elif ${{ inputs.package-manager == 'hatch'}}; then
+    #                     hatch build
+    #                 else
+    #                     echo "Unknown pypi package manager. ${{ inputs.package-manager }} is not part of ['hatch', 'poetry']."
+    #                     exit 1
+    #                 fi
+    #         -   name: Setup JFrog CLI
+    #             uses: jfrog/setup-jfrog-cli@v4.4.1
+    #             env:
+    #                 JF_URL: ${{ secrets.JFROG_ARTIFACTORY_URL }}
+    #                 JF_ACCESS_TOKEN: ${{ secrets.JFROG_ARTIFACTORY_TOKEN }}
+    #         -   name: Publish package to Artifactory
+    #             run: |
+    #                 repository_list=$(echo '${{ inputs.repo-names }}' | jq -r '.[]')
+    #                 for repo_name in ${repository_list}; do
+    #                     jf rt u ${{ env.BUILD_PATH }} ${repo_name}/${{ inputs.package-name }}/${{ inputs.version-tag }}/${{ env.BUILD_NAME }}
+    #                 done
+                    
+                    
+    # release_conda_package:
+    #     name: Release Conda package
+    #     runs-on: ubuntu-latest
+    #     timeout-minutes: ${{ inputs.timeout-minutes }}
+    #     if: ${{ inputs.package-manager == 'conda' }}
+    #     steps:
+    #         -   name: Checkout
+    #             uses: actions/checkout@v2
+    #             with:
+    #                 lfs: ${{ inputs.lfs }}
+    #         -   name: Check if the version tag is available
+    #             run: |
+    #                 if [ "${{ inputs.version-tag }}" = "v0.0.0" ]; then
+    #                     echo "Version tag not available"
+    #                     exit 1
+    #                 else
+    #                     echo "Version tag available"
+    #                 fi
+    #         # -   name: Check if there is a conda recipe
+    #         #     run: |
+    #         #         ls .
+    #         #         if [ -f meta.yaml ]; then
+    #         #             echo "Conda recipe found"
+    #         #         else
+    #         #             echo "Conda recipe not found"
+    #         #             exit 1
+    #         #         fi
+    #         -   name: Setup conda env
+    #             uses: mamba-org/setup-micromamba@v1
+    #             with:
+    #                 micromamba-version: 1.5.8-0
+    #                 environment-name: test_env
+    #                 init-shell: bash
+    #                 cache-downloads: true
+    #             env:
+    #                 PYTHONUTF8: 1
+    #                 CONDA_CHANNEL_PRIORITY: strict
+    #                 PIP_NO_DEPS: 1 # all dependencies are installed from conda
+    #         -   name: Install conda build
+    #             run: conda install -y conda-build conda-verify
+    #         -   name: Build package
+    #             id: build_package
+    #             run: |
+    #                 conda build .
+    #                 build_path=$(conda build --output .)
+    #                 build_name=$(basename ${build_path})
+    #                 echo "BUILD_PATH=${build_path}" >> $GITHUB_ENV
+    #                 echo "BUILD_NAME=${build_name}" >> $GITHUB_ENV
+            
+    #         -   name: Setup JFrog CLI
+    #             uses: jfrog/setup-jfrog-cli@v4.4.1
+    #             env:
+    #                 JF_URL: ${{ secrets.JFROG_ARTIFACTORY_URL }}
+    #                 JF_ACCESS_TOKEN: ${{ secrets.JFROG_ARTIFACTORY_TOKEN }}
+    #         -   name: Publish package to Artifactory
+    #             run: |
+    #                 repository_list=$(echo '${{ inputs.repo-names }}' | jq -r '.[]')
+    #                 for repo_name in ${repository_list}; do
+    #                     jf rt u ${{ env.BUILD_PATH }} ${repo_name}/${{ inputs.package-name }}/${{ inputs.version-tag }}/${{ env.BUILD_NAME }}
+    #                 done
